#!/bin/bash
gcc -O3 -lm ./code/invars/VERT_CHROM.c -o ./bin/invars/VERT_CHROM
gcc -O3 -lm ./code/invars/VERT_CHROM_COUNT.c -o ./bin/invars/VERT_CHROM_COUNT
gcc -O3 -lm ./code/invars/VERT_ANTI_CHROM.c -o ./bin/invars/VERT_ANTI_CHROM
gcc -O3 -lm ./code/invars/VERT_ANTI_CHROM_COUNT.c -o ./bin/invars/VERT_ANTI_CHROM_COUNT
gcc -O3 -lm ./code/invars/MAX_CLIQUE.c -o ./bin/invars/MAX_CLIQUE
gcc -O3 -lm ./code/invars/CLIQUE_NUM.c -o ./bin/invars/CLIQUE_NUM
gcc -O3 -lm ./code/invars/MAX_IND_SET.c -o ./bin/invars/MAX_IND_SET
gcc -O3 -lm ./code/invars/IND_SET_NUM.c -o ./bin/invars/IND_SET_NUM
gcc -O3 -lm ./code/invars/VERT_COVER.c -o ./bin/invars/VERT_COVER
gcc -O3 -lm ./code/invars/MIN_METRIC_DIM.c -o ./bin/invars/MIN_METRIC_DIM
gcc -O3 -lm ./code/invars/MIN_BANDWIDTH.c -o ./bin/invars/MIN_BANDWIDTH
gcc -O3 -lm ./code/invars/MAX_BANDWIDTH.c -o ./bin/invars/MAX_BANDWIDTH
gcc -O3 -lm ./code/invars/MIN_LINEAR_ARRANGEMENT.c -o ./bin/invars/MIN_LINEAR_ARRANGEMENT
gcc -O3 -lm ./code/invars/MAX_LINEAR_ARRANGEMENT.c -o ./bin/invars/MAX_LINEAR_ARRANGEMENT
gcc -O3 -lm ./code/invars/MIN_LINE_CROSSING.c -o ./bin/invars/MIN_LINE_CROSSING
gcc -O3 -lm ./code/invars/MAX_LINE_CROSSING.c -o ./bin/invars/MAX_LINE_CROSSING
gcc -O3 -lm ./code/invars/MIN_CIRCLE_CROSSING.c -o ./bin/invars/MIN_CIRCLE_CROSSING
gcc -O3 -lm ./code/invars/MAX_CIRCLE_CROSSING.c -o ./bin/invars/MAX_CIRCLE_CROSSING
gcc -O3 -lm ./code/invars/IRREGULARITY.c -o ./bin/invars/IRREGULARITY
gcc -O3 -lm ./code/invars/LOVASZ_THETA.c -o ./bin/invars/LOVASZ_THETA
gcc -O3 -lm ./code/invars/MIN_DEG.c -o ./bin/invars/MIN_DEG
gcc -O3 -lm ./code/invars/EDGES.c -o ./bin/invars/EDGES
gcc -O3 -lm ./code/invars/VERTS.c -o ./bin/invars/VERTS
gcc -O3 -lm ./code/invars/TRIANGLES.c -o ./bin/invars/TRIANGLES
gcc -O3 -lm ./code/invars/QUADS.c -o ./bin/invars/QUADS
gcc -O3 -lm ./code/invars/DISTANCE_SUM.c -o ./bin/invars/DISTANCE_SUM
gcc -O3 -lm ./code/invars/CLOSER_PRODUCT.c -o ./bin/invars/CLOSER_PRODUCT
gcc -O3 -lm ./code/invars/CLOSER_DIFF.c -o ./bin/invars/CLOSER_DIFF
gcc -O3 -lm ./code/invars/DIAMETER.c -o ./bin/invars/DIAMETER
gcc -O3 -lm ./code/invars/RADIUS.c -o ./bin/invars/RADIUS
gcc -O3 -lm ./code/invars/CENTER_SUM.c -o ./bin/invars/CENTER_SUM
gcc -O3 -lm ./code/invars/OUTER_SUM.c -o ./bin/invars/OUTER_SUM
gcc -O3 -lm ./code/invars/MAX_CYCLE.c -o ./bin/invars/MAX_CYCLE
gcc -O3 -lm ./code/invars/MIN_CYCLE.c -o ./bin/invars/MIN_CYCLE
gcc -O3 -lm ./code/invars/ODD_CYCLES.c -o ./bin/invars/ODD_CYCLES
gcc -O3 -lm ./code/invars/MIN_MARTIN_CODE.c -o ./bin/invars/MIN_MARTIN_CODE
gcc -O3 -lm ./code/invars/KOCKAY_PARTITIONS.c -o ./bin/invars/KOCKAY_PARTITIONS
gcc -O3 -lm ./code/invars/MIN_GENUS.c -o ./bin/invars/MIN_GENUS
gcc -O3 -lm ./code/invars/RANDIC_INDEX.c -o ./bin/invars/RANDIC_INDEX
